import type { Category, Banner, Product, FeaturedCategory } from "@/types";

export const SITE_NAME = "Boxzz";
export const SITE_TAGLINE = "Premium Corrugated Boxes & Packaging Materials";
export const SITE_DESCRIPTION =
  "Manufacturer of corrugated boxes, packaging tapes, bubble wrap, poly bags, thermal labels, and other packaging materials. GST 12% & freight charges extra.";

export const CURRENCY = {
  symbol: "₹",
  code: "INR",
  locale: "en-IN" as const,
};

// These are fallback defaults. The actual values come from site_settings DB table.
// The store/index.tsx fetches them via getShippingConfig() and caches them.
export const FREE_SHIPPING_THRESHOLD = 499;
export const STANDARD_SHIPPING_CHARGE = 75;
export const GST_RATE = 0.12;

export const CONTACT_INFO = {
  phone: "+91 85700 59569",
  email: "anmolpackagingkarnal@gmail.com",
  address: "New Bahadur Channa Colony, Hansi Road, Karnal - 132001 (Haryana)",
  workingHours: "Mon - Sat: 9:00 AM - 7:00 PM",
};

export const FEATURED_CATEGORIES: FeaturedCategory[] = [
  {
    id: "corrugated-boxes",
    name: "Corrugated Boxes",
    icon: "📦",
    description: "Complete range of 3-ply, 5-ply & 7-ply corrugated boxes. RSC style, flap boxes and white boxes in 60+ standard sizes.",
    shortDescription: "60+ sizes • 3 Ply, 5 Ply & 7 Ply",
    image: "/corugated.png",
    productCount: 74,
    subcategories: ["3-ply-boxes", "3-ply-flap-boxes", "3-ply-white-boxes", "3-ply-flap-white-boxes", "5-ply-boxes", "7-ply-boxes", "corrugated-roll"],
  },
  {
    id: "packaging-tapes",
    name: "Packaging Tapes",
    icon: "🔵",
    description: "BOPP packaging tapes including Flipkart, Amazon Simple, Amazon Prime, Handle With Care, and transparent tapes.",
    shortDescription: "5 types • Box of 36-72 pcs",
    image: "/packaging-tapes.png",
    productCount: 5,
    subcategories: ["packaging-tapes"],
  },
  {
    id: "protective-packaging",
    name: "Protective Packaging",
    icon: "🛡️",
    description: "Eco-friendly paper bubble wrap and poly bags with POD feature. Ideal for wrapping and protecting your shipments.",
    shortDescription: "Bubble wrap & poly bags",
    image: "/protective.png",
    productCount: 3,
    subcategories: ["paper-bubble-wrap", "poly-bags"],
  },
  {
    id: "labels-media",
    name: "Labels & Media",
    icon: "🏷️",
    description: "Thermal label paper in multiple sizes and custom-printed flap boxes with your brand logo.",
    shortDescription: "Labels, printing & custom boxes",
    image: "/label-media.png",
    productCount: 6,
    subcategories: ["thermal-labels", "3-ply-printed-flap-boxes"],
  },
];

export const CATEGORIES: Category[] = [
  {
    id: "3-ply-boxes",
    name: "3 Ply Corrugated Boxes",
    nameHindi: "3 प्लाई नालीदार बक्से",
    icon: "📦",
    description:
      "Standard 3-ply corrugated boxes ideal for lightweight products, e-commerce shipments, and storage. Available in 37 standard sizes from 3.5x3.5x3.5 to 15x11x9 inches.",
    shortDescription: "37 sizes • Starting ₹2.50/piece",
    image: "/images/categories/3ply-boxes.jpg",
    productCount: 37,
  },
  {
    id: "3-ply-flap-boxes",
    name: "3 Ply Flap Boxes",
    nameHindi: "3 प्लाई फ्लैप बक्से",
    icon: "📋",
    description:
      "3-ply boxes with flap lids for easy access and secure closure. Perfect for product packaging, storage, and retail display.",
    shortDescription: "13 sizes • Starting ₹1.75/piece",
    image: "/images/categories/flap-boxes.jpg",
    productCount: 13,
  },
  {
    id: "3-ply-printed-flap-boxes",
    name: "Printed Flap Boxes",
    nameHindi: "प्रिंटेड फ्लैप बक्से",
    icon: "🎨",
    description:
      "Custom-printed 3-ply flap boxes with your brand logo and design. Available in standard sizes with full-color printing.",
    shortDescription: "2 sizes • Starting ₹7.50/piece",
    image: "/images/categories/printed-flap.jpg",
    productCount: 2,
  },
  {
    id: "3-ply-white-boxes",
    name: "3 Ply White Boxes",
    nameHindi: "3 प्लाई सफेद बक्से",
    icon: "⬜",
    description:
      "Clean white finish 3-ply corrugated boxes for premium product presentation. Ideal for cosmetics, gifts, and branded products.",
    shortDescription: "6 sizes • Starting ₹3.50/piece",
    image: "/images/categories/white-boxes.jpg",
    productCount: 6,
  },
  {
    id: "3-ply-flap-white-boxes",
    name: "3 Ply Flap White Boxes",
    nameHindi: "3 प्लाई फ्लैप सफेद बक्से",
    icon: "🤍",
    description:
      "White flap-top boxes combining premium finish with easy-access flap lids. Perfect for retail and gift packaging.",
    shortDescription: "12 sizes • Starting ₹2.15/piece",
    image: "/images/categories/flap-white.jpg",
    productCount: 12,
  },
  {
    id: "5-ply-boxes",
    name: "5 Ply Corrugated Boxes",
    nameHindi: "5 प्लाई नालीदार बक्से",
    icon: "📦",
    description:
      "Heavy-duty 5-ply double-wall corrugated boxes for industrial use, heavy items, and long-distance shipping.",
    shortDescription: "5 sizes • Starting ₹26.00/piece",
    image: "/images/categories/5ply-boxes.jpg",
    productCount: 5,
  },
  {
    id: "7-ply-boxes",
    name: "7 Ply Corrugated Boxes",
    nameHindi: "7 प्लाई नालीदार बक्से",
    icon: "💪",
    description:
      "Extra-heavy duty 7-ply triple-wall boxes for maximum protection. Ideal for industrial machinery, heavy equipment, and bulk shipping.",
    shortDescription: "Starting ₹110.00/piece",
    image: "/images/categories/7ply-boxes.jpg",
    productCount: 1,
  },
  {
    id: "packaging-tapes",
    name: "Packaging Tapes",
    nameHindi: "पैकेजिंग टेप",
    icon: "🔵",
    description:
      "High-quality BOPP packaging tapes including Flipkart tape, Amazon tape, Prime tape, Handle With Care tape, and transparent tape.",
    shortDescription: "5 types • Box of 36-72 pcs",
    image: "/images/categories/tapes.jpg",
    productCount: 5,
  },
  {
    id: "paper-bubble-wrap",
    name: "Paper Bubble Wrap",
    nameHindi: "पेपर बबल रैप",
    icon: "📜",
    description:
      "Eco-friendly paper bubble wrap for protective packaging. 100 meters and 250 meter rolls, 15 inches width.",
    shortDescription: "2 sizes • Starting ₹650/roll",
    image: "/images/categories/bubble-wrap.jpg",
    productCount: 2,
  },
  {
    id: "poly-bags",
    name: "Poly Bags (With POD)",
    nameHindi: "पॉली बैग",
    icon: "🛍️",
    description:
      'Poly bags with POD (Puncture On Delivery) feature. Available in sizes 6x8, 8x10, 10x12, 10x14, 12x16, 14x18, 16x20 inches.',
    shortDescription: "7 sizes • ₹160/kg • 10 kg min",
    image: "/images/categories/poly-bags.jpg",
    productCount: 1,
  },
  {
    id: "thermal-labels",
    name: "Thermal Label Paper",
    nameHindi: "थर्मल लेबल पेपर",
    icon: "🏷️",
    description:
      "High-quality thermal label paper for barcode and shipping labels. Available in 4x6, 3x5, and 1x2 inch sizes.",
    shortDescription: "4 variants • Starting ₹65/pack",
    image: "/images/categories/thermal-labels.jpg",
    productCount: 4,
  },
  {
    id: "corrugated-roll",
    name: "Corrugated Roll",
    nameHindi: "नालीदार रोल",
    icon: "🔄",
    description:
      "Corrugated rolls in sizes 24, 26, 28, 30 inches width. Ideal for custom packaging and layering protection.",
    shortDescription: "4 sizes • ₹50/kg • 50 kg min",
    image: "/images/categories/corrugated-roll.jpg",
    productCount: 1,
  },
  {
    id: "custom-packaging",
    name: "Custom Packaging Solutions",
    nameHindi: "कस्टम पैकेजिंग समाधान",
    icon: "✨",
    description:
      "Custom-sized corrugated boxes, branded packaging with logo printing, and tailor-made packaging solutions for your business needs. Get a free quote today.",
    shortDescription: "Custom sizes • Logo printing • Free quote",
    image: "/images/categories/corrugated-boxes.jpg",
    productCount: 0,
  },
];

export const CUSTOM_PACKAGING_SERVICES = [
  {
    id: "custom-boxes",
    title: "Custom Sized Boxes",
    icon: "📏",
    description: "Need a box that doesn't fit standard sizes? We manufacture boxes in any custom dimension you need. Just share your requirements and we'll make it.",
    features: [
      "Any L x W x H dimensions",
      "3 Ply, 5 Ply, or 7 Ply material",
      "RSC, Flap, or Die-cut styles",
      "Minimum order: 500 pieces",
    ],
    price: "Starting ₹2.50/piece",
  },
  {
    id: "branded-printing",
    title: "Branded & Printed Boxes",
    icon: "🎨",
    description: "Build your brand with custom-printed packaging. Full-color CMYK printing on flap boxes, corrugated boxes, and mailer boxes.",
    features: [
      "Full-color CMYK printing",
      "1-color & 2-color economical options",
      "Your logo, artwork, or design",
      "Pantone color matching available",
    ],
    price: "Starting ₹7.50/piece (incl. print)",
  },
  {
    id: "white-boxes",
    title: "Premium White Boxes",
    icon: "⬜",
    description: "White kraft boxes for premium product presentation. Available in custom sizes with optional printing. Ideal for cosmetics, gifts, and retail.",
    features: [
      "Clean white finish",
      "Custom sizes available",
      "Flap top or RSC style",
      "Optional logo printing",
    ],
    price: "Starting ₹3.50/piece",
  },
  {
    id: "bulk-wholesale",
    title: "Bulk & Wholesale Orders",
    icon: "🏭",
    description: "Manufacturer-direct pricing for bulk and wholesale orders. Best rates for businesses, distributors, and re-sellers across India.",
    features: [
      "Factory-direct pricing",
      "Volume discounts available",
      "PAN India delivery",
      "GST invoice provided",
    ],
    price: "Custom quote based on volume",
  },
];

export const CUSTOM_PACKAGING_STEPS = [
  {
    step: 1,
    title: "Share Your Requirements",
    description: "Tell us your box dimensions, quantity, material preference, and any printing needs.",
    icon: "📝",
  },
  {
    step: 2,
    title: "Get a Free Quote",
    description: "Our team will calculate the best price and share a detailed quotation within 24 hours.",
    icon: "💬",
  },
  {
    step: 3,
    title: "Artwork & Approval",
    description: "For printed boxes, we'll share a digital proof. Approve and we go into production.",
    icon: "✅",
  },
  {
    step: 4,
    title: "Production & Delivery",
    description: "We manufacture and deliver to your doorstep. PAN India shipping with tracking.",
    icon: "🚚",
  },
];

export const BANNERS: Banner[] = [
  {
    id: "banner-1",
    title: "Premium Corrugated Boxes",
    subtitle: "Starting from ₹1.75 per box • 3 Ply, 5 Ply & 7 Ply • 60+ sizes available",
    image: "/slider1.png",
    cta: "View Price List",
    ctaLink: "/category/3-ply-boxes",
    bgColor: "from-primary-50 via-amber-100/50 to-white",
  },
  {
    id: "banner-2",
    title: "Flipkart & Amazon Tapes",
    subtitle: "Official Flipkart tape • Amazon Simple & Prime tape • 60 meters • Box of 48-72 pieces",
    image: "/slider2.png",
    cta: "Shop Tapes",
    ctaLink: "/category/packaging-tapes",
    bgColor: "from-blue-50 via-indigo-100/50 to-white",
  },
];

export const FEATURED_PRODUCTS: Product[] = [
  // ── 3 PLY CORRUGATED BOXES ──
  {
    id: "ply3-001",
    name: '3 Ply Corrugated Box (3.5" x 3.5" x 3.5")',
    slug: "3-ply-corrugated-box-3-5x3-5x3-5",
    description:
      'Standard 3-ply corrugated box measuring 3.5"L x 3.5"W x 3.5"H. Made from high-strength kraft paper. Ideal for small products, mobile accessories, and lightweight items. These boxes are perfect for e-commerce shipments, providing excellent protection for your products during transit. The B-flute construction offers the right balance of strength and cushioning.',
    shortDescription: "Small size box • Best for accessories • High-strength kraft",
    price: 312,
    originalPrice: 428,
    images: ["/corugated.png", "/banner.webp", "/slider1.png"],
    category: "3-ply-boxes",
    subcategory: "3 Ply Corrugated Boxes",
    features: [
      "Lightweight yet strong 3-ply construction",
      "100% recyclable and eco-friendly kraft paper",
      "Easy to fold and assemble in seconds",
      "Stackable design for efficient storage",
      "Suitable for e-commerce, storage & shipping",
      "B-Flute for optimal cushioning",
    ],
    specifications: {
      Material: "Corrugated Kraft Paper",
      Ply: "3",
      Color: "Brown",
      Length: '3.5"',
      Width: '3.5"',
      Height: '3.5"',
      "Box Style": "Regular Slotted Container (RSC)",
      "Flute Type": "B-Flute",
      Weight: "45 g",
      Recyclable: "Yes",
      Reusable: "Yes",
    },
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    stockCount: 50000,
    moq: 1,
    unit: "pack",
    variants: [
      {
        id: "ply3-001-pack50",
        label: "Pack of 50",
        value: "pack50",
        price: 312,
        mrp: 428,
        discount: 27,
        stock: 1000,
        weight: 2.2,
        sku: "BXZ-3PLY-3.5-P50",
        inStock: true,
      },
      {
        id: "ply3-001-pack100",
        label: "Pack of 100",
        value: "pack100",
        price: 590,
        mrp: 780,
        discount: 24,
        stock: 500,
        weight: 4.5,
        sku: "BXZ-3PLY-3.5-P100",
        inStock: true,
      },
      {
        id: "ply3-001-pack200",
        label: "Pack of 200",
        value: "pack200",
        price: 1150,
        mrp: 1550,
        discount: 26,
        stock: 300,
        weight: 9,
        sku: "BXZ-3PLY-3.5-P200",
        inStock: true,
      },
      {
        id: "ply3-001-pack500",
        label: "Pack of 500",
        value: "pack500",
        price: 2780,
        mrp: 3400,
        discount: 18,
        stock: 100,
        weight: 22,
        sku: "BXZ-3PLY-3.5-P500",
        inStock: true,
      },
      {
        id: "ply3-001-pack1000",
        label: "Pack of 1000",
        value: "pack1000",
        price: 5400,
        mrp: 6500,
        discount: 17,
        stock: 50,
        weight: 45,
        sku: "BXZ-3PLY-3.5-P1000",
        inStock: true,
      },
    ],
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    discount: 27,
    customizationAvailable: true,
    printingOptions: ["1-color", "2-color", "Full CMYK"],
    applications: [
      "E-commerce",
      "Courier",
      "Storage",
      "Gift Packaging",
      "Electronics",
      "Jewellery",
      "Cosmetics",
    ],
    createdAt: "2024-01-01",
  },
  {
    id: "ply3-002",
    name: '3 Ply Corrugated Box (4" x 4" x 3")',
    slug: "3-ply-corrugated-box-4x4x3",
    description:
      'Standard 3-ply corrugated box measuring 4"L x 4"W x 3"H. Perfect for e-commerce shipments and product packaging.',
    shortDescription: "Popular e-commerce size • Affordable packaging solution",
    price: 2.75,
    originalPrice: 3.5,
    images: ["/images/products/3ply-002.jpg"],
    category: "3-ply-boxes",
    subcategory: "3 Ply Corrugated Boxes",
    features: [
      "Economical packaging solution",
      "Suitable for e-commerce",
      "Strong & durable construction",
      "Stackable design",
    ],
    rating: 4.7,
    reviewCount: 134,
    inStock: true,
    stockCount: 50000,
    moq: 1000,
    unit: "piece",
    isFeatured: true,
    discount: 21,
    customizationAvailable: true,
    printingOptions: ["1-color", "2-color"],
    createdAt: "2024-01-01",
    specifications: {
      Material: "3 Ply Kraft Paper",
      Length: '4"',
      Width: '4"',
      Height: '3"',
      "Flute Type": "B-Flute",
      MOQ: "1000 pieces",
    },
  },
  {
    id: "ply3-003",
    name: '3 Ply Corrugated Box (5" x 5" x 5") - Most Popular',
    slug: "3-ply-corrugated-box-5x5x5",
    description:
      'Standard 3-ply corrugated box measuring 5"L x 5"W x 5"H. One of our most popular sizes for general purpose packaging and shipping.',
    shortDescription: "Most popular • Versatile mid-size box",
    price: 4.25,
    originalPrice: 5.5,
    images: ["/images/products/3ply-003.jpg"],
    category: "3-ply-boxes",
    subcategory: "3 Ply Corrugated Boxes",
    features: [
      "Most popular mid-size box",
      "Versatile for various products",
      "Excellent stacking strength",
      "Affordable pricing for bulk orders",
    ],
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    stockCount: 100000,
    moq: 1000,
    unit: "piece",
    isFeatured: true,
    isBestSeller: true,
    discount: 23,
    customizationAvailable: true,
    printingOptions: ["1-color", "2-color", "Full CMYK"],
    createdAt: "2024-01-01",
    specifications: {
      Material: "3 Ply Kraft Paper",
      Length: '5"',
      Width: '5"',
      Height: '5"',
      "Flute Type": "B-Flute",
      MOQ: "1000 pieces",
    },
  },
  {
    id: "ply3-007",
    name: '3 Ply Corrugated Box (6" x 6" x 6")',
    slug: "3-ply-corrugated-box-6x6x6",
    description:
      'Standard 3-ply corrugated box measuring 6"L x 6"W x 6"H. Medium-sized box perfect for e-commerce and retail products.',
    shortDescription: "Popular medium size • Ideal for e-commerce",
    price: 6.0,
    originalPrice: 8.0,
    images: ["/images/products/3ply-007.jpg"],
    category: "3-ply-boxes",
    subcategory: "3 Ply Corrugated Boxes",
    features: [
      "Popular medium size",
      "Strong cube design",
      "Ideal for e-commerce",
      "Bulk savings available",
    ],
    rating: 4.8,
    reviewCount: 245,
    inStock: true,
    stockCount: 75000,
    moq: 1000,
    unit: "piece",
    isFeatured: true,
    isBestSeller: true,
    discount: 25,
    customizationAvailable: true,
    printingOptions: ["1-color", "2-color"],
    createdAt: "2024-01-01",
    specifications: {
      Material: "3 Ply Kraft Paper",
      Length: '6"',
      Width: '6"',
      Height: '6"',
      MOQ: "1000 pieces",
    },
  },
  {
    id: "ply3-038",
    name: '3 Ply Corrugated Box (15" x 11" x 9") - Large',
    slug: "3-ply-corrugated-box-15x11x9",
    description:
      'Large 3-ply corrugated box measuring 15"L x 11"W x 9"H. Ideal for oversized products, bulk shipping, and storage.',
    shortDescription: "Large capacity • Reinforced for heavy items",
    price: 20.0,
    originalPrice: 25.0,
    images: ["/images/products/3ply-038.jpg"],
    category: "3-ply-boxes",
    subcategory: "3 Ply Corrugated Boxes",
    features: [
      "Large capacity box",
      "Reinforced for heavy items",
      "Suitable for bulk shipping",
      "Stackable design",
    ],
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    stockCount: 25000,
    moq: 500,
    unit: "piece",
    isFeatured: true,
    discount: 20,
    customizationAvailable: true,
    printingOptions: ["1-color"],
    createdAt: "2024-01-01",
    specifications: {
      Material: "3 Ply Kraft Paper",
      Length: '15"',
      Width: '11"',
      Height: '9"',
      MOQ: "500 pieces",
    },
  },

  // ── 3 PLY FLAP BOXES ──
  {
    id: "flap-001",
    name: '3 Ply Flap Box (4.5" x 3" x 1") - Best Price',
    slug: "3-ply-flap-box-4-5x3x1",
    description:
      '3-ply corrugated box with flap lid measuring 4.5"L x 3"W x 1"H. Our lowest priced product at just ₹1.75 per piece. Ideal for small retail products.',
    shortDescription: "Lowest price • Flap lid • Retail ready",
    price: 1.75,
    originalPrice: 2.5,
    images: ["/images/products/flap-001.jpg"],
    category: "3-ply-flap-boxes",
    subcategory: "3 Ply Flap Boxes",
    features: [
      "Starting from just ₹1.75/piece",
      "Flap lid for easy opening",
      "Perfect for retail packaging",
      "Budget-friendly solution",
      "100% recyclable kraft paper",
    ],
    rating: 4.7,
    reviewCount: 423,
    inStock: true,
    stockCount: 100000,
    moq: 1000,
    unit: "piece",
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    discount: 30,
    customizationAvailable: true,
    printingOptions: ["1-color"],
    createdAt: "2024-06-01",
    specifications: {
      Material: "3 Ply Kraft Paper",
      Length: '4.5"',
      Width: '3"',
      Height: '1"',
      "Box Style": "Flap Box",
      MOQ: "1000 pieces",
    },
  },
  {
    id: "flap-002",
    name: '3 Ply Flap Box (6" x 4" x 2")',
    slug: "3-ply-flap-box-6x4x2",
    description:
      '3-ply corrugated flap box measuring 6"L x 4"W x 2"H. Popular size for gift packaging and retail products.',
    shortDescription: "Popular retail size • Flap lid closure",
    price: 4.0,
    originalPrice: 5.5,
    images: ["/images/products/flap-002.jpg"],
    category: "3-ply-flap-boxes",
    subcategory: "3 Ply Flap Boxes",
    features: [
      "Popular retail size",
      "Flap lid closure",
      "Smooth finish",
      "Custom printing available",
    ],
    rating: 4.6,
    reviewCount: 178,
    inStock: true,
    stockCount: 50000,
    moq: 1000,
    unit: "piece",
    isFeatured: true,
    discount: 27,
    customizationAvailable: true,
    printingOptions: ["1-color", "2-color"],
    createdAt: "2024-01-01",
    specifications: {
      Length: '6"',
      Width: '4"',
      Height: '2"',
      MOQ: "1000 pieces",
    },
  },

  // ── PRINTED FLAP BOXES ──
  {
    id: "printed-001",
    name: '3 Ply Printed Flap Box (6" x 4" x 2")',
    slug: "printed-flap-box-6x4x2",
    description:
      'Custom-printed 3-ply flap box with your brand logo. Size: 6"L x 4"W x 2"H. Full-color printing for premium brand presentation.',
    shortDescription: "Full-color printing • Premium brand packaging",
    price: 7.5,
    originalPrice: 10.0,
    images: ["/images/products/printed-001.jpg"],
    category: "3-ply-printed-flap-boxes",
    subcategory: "Printed Flap Boxes",
    features: [
      "Full-color brand printing",
      "Flap lid with secure closure",
      "Premium presentation quality",
      "Ideal for branded retail packaging",
    ],
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
    stockCount: 25000,
    moq: 1000,
    unit: "piece",
    isFeatured: true,
    isNew: true,
    discount: 25,
    customizationAvailable: true,
    printingOptions: ["Full CMYK", "1-color", "2-color"],
    createdAt: "2024-06-01",
    specifications: {
      Material: "3 Ply Kraft with Print",
      Length: '6"',
      Width: '4"',
      Height: '2"',
      Printing: "Full Color CMYK",
      MOQ: "1000 pieces",
    },
  },

  // ── 5 PLY BOXES ──
  {
    id: "ply5-001",
    name: '5 Ply Heavy-Duty Box (12" x 12" x 12")',
    slug: "5-ply-box-12x12x12",
    description:
      'Heavy-duty 5-ply double-wall corrugated box measuring 12"L x 12"W x 12"H. For heavy items, industrial use, and long-distance shipping.',
    shortDescription: "Heavy-duty 5-ply • Double-wall construction",
    price: 40.0,
    originalPrice: 50.0,
    images: ["/images/products/5ply-001.jpg"],
    category: "5-ply-boxes",
    subcategory: "5 Ply Corrugated Boxes",
    features: [
      "Double-wall 5-ply construction",
      "Heavy load capacity",
      "Crush-proof design",
      "Ideal for industrial shipping",
    ],
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    stockCount: 10000,
    moq: 100,
    unit: "piece",
    isFeatured: true,
    isBestSeller: true,
    discount: 20,
    customizationAvailable: true,
    printingOptions: ["1-color"],
    createdAt: "2024-01-01",
    specifications: {
      Material: "5 Ply (Double Wall)",
      Length: '12"',
      Width: '12"',
      Height: '12"',
      "Flute Type": "BC-Flute",
      MOQ: "100 pieces",
    },
  },
  {
    id: "ply5-002",
    name: '5 Ply Heavy-Duty Box (18" x 12" x 12")',
    slug: "5-ply-box-18x12x12",
    description:
      'Large 5-ply double-wall box measuring 18"L x 12"W x 12"H. Perfect for heavy industrial products and bulk shipping.',
    shortDescription: "Extra-large size • Maximum protection",
    price: 50.0,
    originalPrice: 65.0,
    images: ["/images/products/5ply-002.jpg"],
    category: "5-ply-boxes",
    subcategory: "5 Ply Corrugated Boxes",
    features: [
      "Extra-large size",
      "Maximum protection",
      "Industrial grade",
      "Stackable & sturdy",
    ],
    rating: 4.8,
    reviewCount: 56,
    inStock: true,
    stockCount: 8000,
    moq: 100,
    unit: "piece",
    isFeatured: true,
    discount: 23,
    customizationAvailable: true,
    printingOptions: ["1-color"],
    createdAt: "2024-01-01",
    specifications: {
      Length: '18"',
      Width: '12"',
      Height: '12"',
      MOQ: "100 pieces",
    },
  },

  // ── 7 PLY BOX ──
  {
    id: "ply7-001",
    name: '7 Ply Extra-Heavy Box (27" x 13" x 14")',
    slug: "7-ply-box-27x13x14",
    description:
      'Industrial-grade 7-ply triple-wall corrugated box measuring 27"L x 13"W x 14"H. Maximum strength for the heaviest loads and long-distance shipping.',
    shortDescription: "Industrial-grade • Triple-wall construction",
    price: 110.0,
    originalPrice: 130.0,
    images: ["/images/products/7ply-001.jpg"],
    category: "7-ply-boxes",
    subcategory: "7 Ply Corrugated Boxes",
    features: [
      "Triple-wall 7-ply construction",
      "Maximum load capacity",
      "Industrial & export grade",
      "Highest protection level",
    ],
    rating: 5.0,
    reviewCount: 34,
    inStock: true,
    stockCount: 5000,
    moq: 100,
    unit: "piece",
    isFeatured: true,
    discount: 15,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      Material: "7 Ply (Triple Wall)",
      Length: '27"',
      Width: '13"',
      Height: '14"',
      "Flute Type": "BC-Flute",
      MOQ: "100 pieces",
    },
  },

  // ── PACKAGING TAPES ──
  {
    id: "tape-001",
    name: "Flipkart Tape (60mtr x 48mm)",
    slug: "flipkart-tape-60mtr-48mm",
    description:
      "Official Flipkart-compatible BOPP packaging tape. 60 meters length, 48mm width. Sold in box of 72 pieces. Perfect for e-commerce sellers.",
    shortDescription: "Flipkart compatible • Box of 72 pieces",
    price: 1800,
    originalPrice: 2200,
    images: ["/images/products/tape-flipkart.jpg"],
    category: "packaging-tapes",
    subcategory: "BOPP Tapes",
    features: [
      "Flipkart compatible tape",
      "60 meters per roll",
      "Box of 72 pieces",
      "High tensile strength",
      "Clear acrylic adhesive",
    ],
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    stockCount: 2000,
    moq: 1,
    unit: "box",
    isFeatured: true,
    isBestSeller: true,
    discount: 18,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      "Tape Type": "Flipkart Tape",
      Length: "60 meters",
      Width: "48mm",
      "Pack Size": "72 pieces per box",
      Adhesive: "Acrylic",
    },
  },
  {
    id: "tape-002",
    name: "Amazon Simple Tape (60mtr x 48mm)",
    slug: "amazon-simple-tape-60mtr-48mm",
    description:
      "Amazon Simple-compatible BOPP packaging tape. 60 meters length, 48mm width. Box of 72 pieces. Ideal for Amazon sellers.",
    shortDescription: "Amazon Simple compatible • Box of 72",
    price: 1800,
    originalPrice: 2200,
    images: ["/images/products/tape-amazon.jpg"],
    category: "packaging-tapes",
    subcategory: "BOPP Tapes",
    features: [
      "Amazon Simple compatible",
      "60 meters per roll",
      "Box of 72 pieces",
      "Strong acrylic adhesive",
      "No residue on removal",
    ],
    rating: 4.6,
    reviewCount: 189,
    inStock: true,
    stockCount: 2000,
    moq: 1,
    unit: "box",
    isFeatured: true,
    discount: 18,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      "Tape Type": "Amazon Simple Tape",
      Length: "60 meters",
      Width: "48mm",
      "Pack Size": "72 pieces per box",
    },
  },
  {
    id: "tape-003",
    name: "Amazon Prime Tape (60mtr x 72mm)",
    slug: "amazon-prime-tape-60mtr-72mm",
    description:
      "Amazon Prime-compatible wide BOPP tape. 60 meters length, 72mm width. Box of 48 pieces. Premium tape for Prime sellers.",
    shortDescription: "Amazon Prime compatible • 72mm wide",
    price: 2000,
    originalPrice: 2500,
    images: ["/images/products/tape-prime.jpg"],
    category: "packaging-tapes",
    subcategory: "BOPP Tapes",
    features: [
      "Amazon Prime compatible",
      "Wider 72mm for extra grip",
      "60 meters per roll",
      "Box of 48 pieces",
      "Premium quality",
    ],
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    stockCount: 1500,
    moq: 1,
    unit: "box",
    isFeatured: true,
    isNew: true,
    discount: 20,
    customizationAvailable: false,
    createdAt: "2024-06-01",
    specifications: {
      "Tape Type": "Amazon Prime Tape",
      Length: "60 meters",
      Width: "72mm",
      "Pack Size": "48 pieces per box",
    },
  },
  {
    id: "tape-004",
    name: 'Handle With Care Tape (60mtr x 48mm)',
    slug: "handle-with-care-tape-60mtr-48mm",
    description:
      'Yellow "Handle With Care" printed BOPP tape. 60 meters length, 48mm width. Box of 72 pieces. Alerts handlers for fragile packages.',
    shortDescription: '"Handle With Care" • Warning tape',
    price: 1800,
    originalPrice: 2200,
    images: ["/images/products/tape-care.jpg"],
    category: "packaging-tapes",
    subcategory: "Specialty Tapes",
    features: [
      '"Handle With Care" printed',
      "Yellow warning tape",
      "60 meters per roll",
      "Box of 72 pieces",
      "High-visibility design",
    ],
    rating: 4.7,
    reviewCount: 98,
    inStock: true,
    stockCount: 1800,
    moq: 1,
    unit: "box",
    isFeatured: true,
    discount: 18,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      "Tape Type": "Handle With Care Tape",
      Length: "60 meters",
      Width: "48mm",
      "Pack Size": "72 pieces per box",
    },
  },
  {
    id: "tape-005",
    name: "Transparent Tape (220mtr x 48mm)",
    slug: "transparent-tape-220mtr-48mm",
    description:
      "Industrial-grade transparent BOPP tape. Extra-long 220 meters per roll, 48mm width. Box of 36 pieces. Best value for high-volume packing.",
    shortDescription: "Ultra-long 220mtr • Best value for bulk",
    price: 2850,
    originalPrice: 3500,
    images: ["/images/products/tape-transparent.jpg"],
    category: "packaging-tapes",
    subcategory: "BOPP Tapes",
    features: [
      "Ultra-long 220 meters per roll",
      "Best value for bulk packing",
      "Box of 36 pieces",
      "High clarity transparent",
      "Industrial strength",
    ],
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    stockCount: 1200,
    moq: 1,
    unit: "box",
    isFeatured: true,
    isBestSeller: true,
    discount: 19,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      "Tape Type": "Transparent Tape",
      Length: "220 meters",
      Width: "48mm",
      "Pack Size": "36 pieces per box",
    },
  },

  // ── PAPER BUBBLE WRAP ──
  {
    id: "bubble-001",
    name: "Paper Bubble Wrap (100mtr x 15 inch)",
    slug: "paper-bubble-wrap-100mtr-15inch",
    description:
      "Eco-friendly paper bubble wrap roll. 100 meters length, 15 inches width. 4 rolls per pack. Ideal for wrapping fragile items.",
    shortDescription: "Eco-friendly • 100mtr roll • 15 inch width",
    price: 650,
    originalPrice: 800,
    images: ["/images/products/bubble-100.jpg"],
    category: "paper-bubble-wrap",
    subcategory: "Paper Bubble Wrap",
    features: [
      "100% recyclable paper",
      "100 meters per roll",
      "15 inch width",
      "4 pieces per pack",
      "Eco-friendly alternative",
    ],
    rating: 4.5,
    reviewCount: 76,
    inStock: true,
    stockCount: 5000,
    moq: 4,
    unit: "piece",
    isFeatured: true,
    discount: 19,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      Type: "Paper Bubble Wrap",
      Length: "100 meters",
      Width: "15 inches",
      "Pack Size": "4 pieces",
      Material: "Recycled Paper",
    },
  },

  // ── THERMAL LABELS ──
  {
    id: "thermal-001",
    name: 'Thermal Label Paper (4" x 6") - 400 Labels',
    slug: "thermal-label-4x6-400",
    description:
      'High-quality thermal label paper size 4" x 6". Each pack contains 30 rolls with 400 labels each. Perfect for shipping labels and barcodes.',
    shortDescription: '4x6" labels • 30 rolls x 400 labels',
    price: 200,
    originalPrice: 250,
    images: ["/images/products/thermal-4x6.jpg"],
    category: "thermal-labels",
    subcategory: "Thermal Label Paper",
    features: [
      "High-quality thermal paper",
      'Size: 4" x 6"',
      "30 rolls per pack",
      "400 labels per roll",
      "Compatible with all thermal printers",
    ],
    rating: 4.6,
    reviewCount: 134,
    inStock: true,
    stockCount: 10000,
    moq: 30,
    unit: "piece",
    isFeatured: true,
    isBestSeller: true,
    discount: 20,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      "Label Size": '4" x 6"',
      Type: "Direct Thermal",
      "Rolls per Pack": "30",
      "Labels per Roll": "400",
      Compatibility: "All Thermal Printers",
    },
  },
  {
    id: "thermal-002",
    name: 'Thermal Label Paper (3" x 5") - 500 Labels',
    slug: "thermal-label-3x5-500",
    description:
      'Compact thermal label paper size 3" x 5". Each pack contains 30 rolls with 500 labels each. Perfect for price tags and smaller labels.',
    shortDescription: '3x5" labels • 30 rolls x 500 labels',
    price: 150,
    originalPrice: 180,
    images: ["/images/products/thermal-3x5.jpg"],
    category: "thermal-labels",
    subcategory: "Thermal Label Paper",
    features: [
      "Compact size labels",
      "500 labels per roll",
      "30 rolls per pack",
      "Ideal for price tags",
    ],
    rating: 4.5,
    reviewCount: 78,
    inStock: true,
    stockCount: 8000,
    moq: 30,
    unit: "piece",
    isFeatured: true,
    discount: 17,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      "Label Size": '3" x 5"',
      Type: "Direct Thermal",
      "Rolls per Pack": "30",
    },
  },
  {
    id: "thermal-003",
    name: 'Thermal Label (1" x 2" - 1up) - 10000 Labels',
    slug: "thermal-label-1x2-10000",
    description:
      'Small 1" x 2" thermal labels for price marking and small item labeling. 10000 labels per roll, 30 rolls per pack.',
    shortDescription: '1x2" labels • 10000 per roll',
    price: 65,
    originalPrice: 85,
    images: ["/images/products/thermal-1x2.jpg"],
    category: "thermal-labels",
    subcategory: "Thermal Label Paper",
    features: [
      "Small size for price marking",
      "10000 labels per roll",
      "30 rolls per pack",
      "Budget-friendly",
    ],
    rating: 4.4,
    reviewCount: 45,
    inStock: true,
    stockCount: 12000,
    moq: 30,
    unit: "piece",
    discount: 24,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      "Label Size": '1" x 2"',
      "Labels per Roll": "10000",
    },
  },
  {
    id: "thermal-004",
    name: 'Thermal Label (2" x 1" - 2up) - 10000 Labels',
    slug: "thermal-label-2x1-2up-10000",
    description:
      'Two-up 2" x 1" thermal labels for dual-label applications. 10000 labels per roll, 30 rolls per pack.',
    shortDescription: '2x1" 2up labels • 10000 per roll',
    price: 75,
    originalPrice: 95,
    images: ["/images/products/thermal-2x1.jpg"],
    category: "thermal-labels",
    subcategory: "Thermal Label Paper",
    features: [
      "Two-up format for dual labeling",
      "10000 labels per roll",
      "30 rolls per pack",
    ],
    rating: 4.3,
    reviewCount: 34,
    inStock: true,
    stockCount: 10000,
    moq: 30,
    unit: "piece",
    discount: 21,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      "Label Size": '2" x 1" (2up)',
      "Labels per Roll": "10000",
    },
  },

  // ── POLY BAGS ──
  {
    id: "poly-001",
    name: 'Poly Bag (6" x 8") - With POD, 10 kg pack',
    slug: "poly-bag-6x8-pod-10kg",
    description:
      'Poly bag size 6" x 8" with POD (Puncture On Delivery) feature. Sold per kg (approximately 500+ pieces per kg). Minimum order 10 kg.',
    shortDescription: '6x8" With POD • ~500 pcs/kg • 10kg min',
    price: 160,
    originalPrice: 200,
    images: ["/images/products/poly-6x8.jpg"],
    category: "poly-bags",
    subcategory: "Poly Bags",
    features: [
      "POD (Puncture On Delivery) feature",
      "High-quality virgin material",
      "Approx. 500+ pieces per kg",
      "10 kg minimum order",
    ],
    rating: 4.5,
    reviewCount: 67,
    inStock: true,
    stockCount: 5000,
    moq: 10,
    unit: "kg",
    isFeatured: true,
    discount: 20,
    customizationAvailable: false,
    createdAt: "2024-01-01",
    specifications: {
      Size: '6" x 8"',
      Feature: "With POD",
      "Pack Size": "Per Kg (~500+ pcs)",
      MOQ: "10 kg",
    },
  },
];

// Helper for shipping config from DB - can be dynamically fetched
export const INDIAN_STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
  "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab",
  "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
  "Uttar Pradesh", "Uttarakhand", "West Bengal",
  "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry",
];

export const PAYMENT_METHODS = [
  { id: "cod", name: "Cash on Delivery", icon: "💵" },
  { id: "bank-transfer", name: "Bank Transfer (NEFT/IMPS)", icon: "🏦" },
  { id: "upi", name: "UPI / GPay / PhonePe", icon: "📱" },
];